#ifndef _AVS_COMMON_H_
#define _AVS_COMMON_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include <memory.h>
#include "Avs_Base.h"

enum AVS_RADAR_INVALID_STATES {
	AVS_RADAR_INVALID_STATE_VALID			= 0,
	AVS_RADAR_INVALID_STATE_OTHER_VALID		= 1,
	AVS_RADAR_INVALID_STATE_OTHER_INVALID	= 2,
};

enum AVS_RADAR_DYNPROP_STATES {
	AVS_RADAR_DYNPROP_STATE_MOVING					= 0,
	AVS_RADAR_DYNPROP_STATE_STATIONARY				= 1,
	AVS_RADAR_DYNPROP_STATE_ONCOMING				= 2,
	AVS_RADAR_DYNPROP_STATE_STATIONARY_CANDIDATE	= 3,
	AVS_RADAR_DYNPROP_STATE_UNKNOWN					= 4,
	AVS_RADAR_DYNPROP_STATE_CROSSING_STATIONARY		= 5,
	AVS_RADAR_DYNPROP_STATE_CROSSING_MOVING			= 6,
	AVS_RADAR_DYNPROP_STATE_STOPPED					= 7,
};

enum AVS_RADAR_AMBIG_STATES {
	AVS_RADAR_AMBIG_STATE_INVALID				= 0,
	AVS_RADAR_AMBIG_STATE_AMBIGUOUS				= 1,
	AVS_RADAR_AMBIG_STATE_STAGGERED_RAMP		= 2,
	AVS_RADAR_AMBIG_STATE_UNAMBIGUOUS			= 3,
	AVS_RADAR_AMBIG_STATE_STATIONARY_CANDIDATE	= 4,
};

//enum AVS_RADAR_OBJ_CLASS {
//	AVS_RADAR_OBJ_BACKGROUND					= 0,
//	AVS_RADAR_OBJ_CAR							= 1,
//	AVS_RADAR_OBJ_BUS							= 2,
//	AVS_RADAR_OBJ_MOTORCYCLE					= 3,
//	AVS_RADAR_OBJ_TRAILER						= 4,
//	AVS_RADAR_OBJ_TRUCK							= 5,
//	AVS_RADAR_OBJ_BIBYCLE						= 6,
//	AVS_RADAR_OBJ_HUMAN							= 7,
//	AVS_RADAR_OBJ_END							= 8,
//};

enum AVS_RADAR_OBJ_CLASS {
	AVS_RADAR_OBJ_HUMAN			= 0,
	AVS_RADAR_OBJ_BIBYCLE		= 1,
	AVS_RADAR_OBJ_BUS			= 2,
	AVS_RADAR_OBJ_CAR			= 3,
	AVS_RADAR_OBJ_MOTORCYCLE	= 4,
	AVS_RADAR_OBJ_TRAILER		= 5,
	AVS_RADAR_OBJ_TRUCK			= 6,
	AVS_RADAR_OBJ_BACKGROUND	= 7,
	AVS_RADAR_OBJ_END			= 8,
};

enum AVS_LIDAR_OBJ_CLASS {
	AVS_LADAR_OBJ_CYCLIST		= 0,
	AVS_LADAR_OBJ_PEDESTRIAN	= 1,
	AVS_LADAR_OBJ_END			= 2,
};

#ifdef __cplusplus
}
#endif

#endif